create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	price NUMERIC(19,2) NOT NULL	
);
insert into car (make, model, price) values ('Dodge', 'Avenger', '24073.63');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '60104.51');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '87719.97');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '32894.68');
insert into car (make, model, price) values ('Chevrolet', 'Aveo', '94019.81');
insert into car (make, model, price) values ('BMW', 'M', '24098.80');
insert into car (make, model, price) values ('Ford', 'F350', '14964.11');
insert into car (make, model, price) values ('Mazda', 'B2600', '45209.54');
insert into car (make, model, price) values ('Ford', 'F350', '22491.70');
insert into car (make, model, price) values ('Ford', 'Escape', '22407.69');
insert into car (make, model, price) values ('Dodge', 'Durango', '16662.97');
insert into car (make, model, price) values ('Bentley', 'Continental Flying Spur', '21301.27');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '43699.96');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '75681.85');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '47020.05');
insert into car (make, model, price) values ('Volkswagen', 'Golf III', '62363.71');
insert into car (make, model, price) values ('Ford', 'E150', '73518.46');
insert into car (make, model, price) values ('Infiniti', 'G37', '79186.82');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '46282.96');
insert into car (make, model, price) values ('Buick', 'Lucerne', '42717.50');
insert into car (make, model, price) values ('Chrysler', 'Crossfire', '54397.30');
insert into car (make, model, price) values ('Ford', 'E250', '31098.53');
insert into car (make, model, price) values ('Rolls-Royce', 'Phantom', '39608.26');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '48581.66');
insert into car (make, model, price) values ('Honda', 'S2000', '78480.09');
insert into car (make, model, price) values ('Acura', 'MDX', '66819.62');
insert into car (make, model, price) values ('Volvo', 'V70', '69919.73');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '23431.05');
insert into car (make, model, price) values ('Buick', 'Special', '90300.26');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '55844.24');
insert into car (make, model, price) values ('Suzuki', 'XL-7', '67926.05');
insert into car (make, model, price) values ('Volvo', 'S60', '38186.59');
insert into car (make, model, price) values ('Aston Martin', 'DBS', '14163.34');
insert into car (make, model, price) values ('Volvo', 'XC70', '68192.18');
insert into car (make, model, price) values ('Isuzu', 'VehiCROSS', '40210.17');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '83964.83');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '39996.03');
insert into car (make, model, price) values ('Acura', 'TSX', '2158.74');
insert into car (make, model, price) values ('Mercury', 'Lynx', '30737.82');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '39124.54');
insert into car (make, model, price) values ('Toyota', '4Runner', '81026.77');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '55331.29');
insert into car (make, model, price) values ('Audi', 'S8', '96040.45');
insert into car (make, model, price) values ('BMW', 'X6 M', '44251.12');
insert into car (make, model, price) values ('Honda', 'Pilot', '29150.99');
insert into car (make, model, price) values ('Chevrolet', 'SSR', '59751.22');
insert into car (make, model, price) values ('Porsche', 'Boxster', '31609.84');
insert into car (make, model, price) values ('Hyundai', 'Excel', '72235.39');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 2500', '86440.09');
insert into car (make, model, price) values ('Audi', '100', '38643.30');
insert into car (make, model, price) values ('Chrysler', '300M', '74539.82');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '80294.75');
insert into car (make, model, price) values ('Mazda', 'B2000', '64499.47');
insert into car (make, model, price) values ('Hyundai', 'Veloster', '4324.84');
insert into car (make, model, price) values ('Volvo', 'S60', '19483.54');
insert into car (make, model, price) values ('Dodge', 'Viper', '31648.15');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '40016.66');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '2144.56');
insert into car (make, model, price) values ('Volvo', 'C70', '90779.34');
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', '99790.72');
insert into car (make, model, price) values ('Ford', 'Aspire', '39186.12');
insert into car (make, model, price) values ('Porsche', 'Boxster', '41489.10');
insert into car (make, model, price) values ('Volvo', 'V50', '21545.90');
insert into car (make, model, price) values ('Volvo', 'XC90', '26978.88');
insert into car (make, model, price) values ('Land Rover', 'Defender', '2616.58');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '12486.07');
insert into car (make, model, price) values ('Lotus', 'Elan', '81714.20');
insert into car (make, model, price) values ('Honda', 'Pilot', '8072.29');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '76133.91');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '17980.41');
insert into car (make, model, price) values ('Ford', 'Courier', '28348.25');
insert into car (make, model, price) values ('Toyota', 'Camry', '5036.49');
insert into car (make, model, price) values ('Audi', 'S4', '14966.56');
insert into car (make, model, price) values ('Mercury', 'Cougar', '40554.36');
insert into car (make, model, price) values ('BMW', '760', '72083.71');
insert into car (make, model, price) values ('Ford', 'F250', '49170.46');
insert into car (make, model, price) values ('Audi', 'S4', '24612.43');
insert into car (make, model, price) values ('Subaru', 'SVX', '30859.71');
insert into car (make, model, price) values ('Ford', 'Galaxie', '73992.72');
insert into car (make, model, price) values ('Lotus', 'Esprit', '65175.58');
insert into car (make, model, price) values ('Honda', 'S2000', '56951.99');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '12336.53');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '42016.95');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '65537.38');
insert into car (make, model, price) values ('Toyota', 'Sienna', '52729.49');
insert into car (make, model, price) values ('Hyundai', 'Genesis Coupe', '16315.24');
insert into car (make, model, price) values ('Hyundai', 'Accent', '88393.92');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '7781.47');
insert into car (make, model, price) values ('Honda', 'Civic', '74375.39');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '5878.90');
insert into car (make, model, price) values ('Bentley', 'Continental GTC', '6162.77');
insert into car (make, model, price) values ('Kia', 'Spectra', '65395.48');
insert into car (make, model, price) values ('Suzuki', 'Swift', '67002.70');
insert into car (make, model, price) values ('Mercury', 'Lynx', '85661.62');
insert into car (make, model, price) values ('Mercedes-Benz', '400SEL', '53729.08');
insert into car (make, model, price) values ('Ferrari', '430 Scuderia', '90419.87');
insert into car (make, model, price) values ('Saturn', 'L-Series', '58859.71');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '96146.21');
insert into car (make, model, price) values ('Honda', 'Odyssey', '21756.98');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '42037.17');
insert into car (make, model, price) values ('GMC', 'Safari', '40287.89');
insert into car (make, model, price) values ('Buick', 'LeSabre', '55850.95');
insert into car (make, model, price) values ('Holden', 'VS Commodore', '53625.88');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '30972.76');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '16964.24');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '67623.01');
insert into car (make, model, price) values ('Kia', 'Amanti', '42070.32');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '84779.38');
insert into car (make, model, price) values ('Ford', 'Expedition', '11840.44');
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', '18542.11');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '4056.75');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '83736.83');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '58389.38');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '42448.27');
insert into car (make, model, price) values ('Dodge', 'Neon', '11098.18');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '96481.88');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '94304.28');
insert into car (make, model, price) values ('Isuzu', 'Hombre Space', '97958.59');
insert into car (make, model, price) values ('Subaru', 'Legacy', '58346.00');
insert into car (make, model, price) values ('Ford', 'E-Series', '18804.87');
insert into car (make, model, price) values ('Mercedes-Benz', 'W126', '63013.58');
insert into car (make, model, price) values ('Audi', 'S5', '56204.07');
insert into car (make, model, price) values ('Suzuki', 'SJ', '59454.39');
insert into car (make, model, price) values ('Infiniti', 'G', '45587.40');
insert into car (make, model, price) values ('Nissan', 'Quest', '43773.60');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '25594.70');
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', '94791.85');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '89801.22');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '77274.82');
insert into car (make, model, price) values ('Toyota', 'Ipsum', '44516.35');
insert into car (make, model, price) values ('Ford', 'Mustang', '3016.62');
insert into car (make, model, price) values ('Honda', 'Passport', '2376.47');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '9571.86');
insert into car (make, model, price) values ('Mercury', 'Cougar', '87795.93');
insert into car (make, model, price) values ('Isuzu', 'Stylus', '21489.68');
insert into car (make, model, price) values ('Plymouth', 'Laser', '97333.27');
insert into car (make, model, price) values ('Audi', 'R8', '66071.49');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '43508.60');
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', '75659.21');
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G10', '90152.15');
insert into car (make, model, price) values ('Acura', 'CL', '69854.89');
insert into car (make, model, price) values ('Saturn', 'S-Series', '26225.43');
insert into car (make, model, price) values ('Mitsubishi', 'Precis', '72930.93');
insert into car (make, model, price) values ('Mercury', 'Villager', '30736.17');
insert into car (make, model, price) values ('Lincoln', 'Continental', '19321.48');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '64636.91');
insert into car (make, model, price) values ('Mercury', 'Monterey', '73125.95');
insert into car (make, model, price) values ('Maybach', '57', '98920.81');
insert into car (make, model, price) values ('Maybach', '62', '59178.56');
insert into car (make, model, price) values ('BMW', '600', '59150.26');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '98984.13');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '19666.00');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '85987.32');
insert into car (make, model, price) values ('Nissan', 'Versa', '20978.70');
insert into car (make, model, price) values ('Honda', 'Prelude', '51178.08');
insert into car (make, model, price) values ('Kia', 'Sedona', '4531.23');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '85464.66');
insert into car (make, model, price) values ('GMC', 'Vandura 3500', '55016.42');
insert into car (make, model, price) values ('Hyundai', 'Accent', '77149.92');
insert into car (make, model, price) values ('Maserati', 'Spyder', '51580.26');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '92827.34');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '64242.55');
insert into car (make, model, price) values ('Ford', 'F450', '67651.46');
insert into car (make, model, price) values ('Volkswagen', 'Touareg 2', '96434.67');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '81455.58');
insert into car (make, model, price) values ('Mazda', 'Millenia', '53706.20');
insert into car (make, model, price) values ('Lexus', 'LX', '64806.65');
insert into car (make, model, price) values ('GMC', '1500', '15209.96');
insert into car (make, model, price) values ('Mitsubishi', 'GTO', '69427.97');
insert into car (make, model, price) values ('Bentley', 'Azure', '18339.22');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '36626.93');
insert into car (make, model, price) values ('Volvo', 'S90', '83549.88');
insert into car (make, model, price) values ('Ford', 'Explorer', '13752.79');
insert into car (make, model, price) values ('GMC', 'Jimmy', '62632.63');
insert into car (make, model, price) values ('BMW', '330', '70727.02');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '68458.43');
insert into car (make, model, price) values ('Mercedes-Benz', 'R-Class', '74250.94');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '19557.77');
insert into car (make, model, price) values ('Honda', 'Insight', '5789.69');
insert into car (make, model, price) values ('Dodge', 'Dakota', '54115.05');
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', '43267.78');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '57269.09');
insert into car (make, model, price) values ('Nissan', '200SX', '3910.16');
insert into car (make, model, price) values ('BMW', 'X5', '75348.03');
insert into car (make, model, price) values ('Ford', 'E-Series', '42840.82');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '27995.40');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '32151.99');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '37527.45');
insert into car (make, model, price) values ('Ford', 'Focus', '70922.83');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '53801.91');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 2500', '11372.08');
insert into car (make, model, price) values ('Saab', '9-3', '6916.32');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '6432.35');
insert into car (make, model, price) values ('Mercedes-Benz', '400E', '38762.19');
insert into car (make, model, price) values ('Volvo', 'S40', '54604.17');
insert into car (make, model, price) values ('Dodge', 'Caliber', '80568.68');
insert into car (make, model, price) values ('Toyota', 'Corolla', '1703.09');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '34442.85');
insert into car (make, model, price) values ('Audi', 'A4', '58584.10');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '80726.90');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '3907.81');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '50174.01');
insert into car (make, model, price) values ('Daewoo', 'Lanos', '7638.71');
insert into car (make, model, price) values ('BMW', 'M', '35677.69');
insert into car (make, model, price) values ('Subaru', 'XT', '91739.73');
insert into car (make, model, price) values ('Kia', 'Amanti', '28384.50');
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', '40658.48');
insert into car (make, model, price) values ('Volkswagen', 'Scirocco', '81594.67');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '19188.55');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '20626.24');
insert into car (make, model, price) values ('Volkswagen', 'Fox', '14140.40');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '98797.05');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '25098.06');
insert into car (make, model, price) values ('Toyota', 'Camry', '14223.09');
insert into car (make, model, price) values ('Hyundai', 'Tucson', '71615.78');
insert into car (make, model, price) values ('Honda', 'Accord', '93248.48');
insert into car (make, model, price) values ('Kia', 'Sportage', '97212.92');
insert into car (make, model, price) values ('Audi', '90', '16055.25');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '77713.22');
insert into car (make, model, price) values ('Acura', 'NSX', '89675.58');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '61569.49');
insert into car (make, model, price) values ('Subaru', 'Tribeca', '75954.51');
insert into car (make, model, price) values ('Pontiac', 'Aztek', '11196.33');
insert into car (make, model, price) values ('Lotus', 'Esprit', '49819.44');
insert into car (make, model, price) values ('Mazda', 'B2000', '72816.57');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '21576.96');
insert into car (make, model, price) values ('Honda', 'Civic', '28928.39');
insert into car (make, model, price) values ('Chrysler', 'Crossfire', '42291.06');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '41670.71');
insert into car (make, model, price) values ('Nissan', 'Sentra', '63969.67');
insert into car (make, model, price) values ('Lexus', 'RX', '45268.23');
insert into car (make, model, price) values ('Volvo', '850', '81519.12');
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', '47061.35');
insert into car (make, model, price) values ('Mazda', 'CX-7', '69433.69');
insert into car (make, model, price) values ('Ford', 'E350', '93355.34');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '18062.73');
insert into car (make, model, price) values ('GMC', 'Savana', '8363.69');
insert into car (make, model, price) values ('Volvo', 'V70', '81189.21');
insert into car (make, model, price) values ('Ford', 'E-Series', '19247.15');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '5391.13');
insert into car (make, model, price) values ('Kia', 'Amanti', '27870.52');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '68755.56');
insert into car (make, model, price) values ('Acura', 'Legend', '94895.69');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '38271.73');
insert into car (make, model, price) values ('Morgan', 'Aero 8', '67783.65');
insert into car (make, model, price) values ('Honda', 'del Sol', '95029.94');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '54781.03');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '41379.32');
insert into car (make, model, price) values ('Isuzu', 'Hombre Space', '30708.76');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '78790.29');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '35457.74');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '13388.24');
insert into car (make, model, price) values ('Mercury', 'Topaz', '19201.09');
insert into car (make, model, price) values ('Ford', 'Taurus X', '77530.71');
insert into car (make, model, price) values ('Porsche', '911', '71129.09');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '99775.52');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '6878.88');
insert into car (make, model, price) values ('Chevrolet', '1500', '27012.57');
insert into car (make, model, price) values ('Subaru', 'Impreza', '26660.08');
insert into car (make, model, price) values ('Dodge', 'Ram 3500 Club', '9775.99');
insert into car (make, model, price) values ('Cadillac', 'Catera', '34675.47');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '44979.71');
insert into car (make, model, price) values ('Pontiac', 'Vibe', '20307.26');
insert into car (make, model, price) values ('Jeep', 'Patriot', '61546.29');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '7929.14');
insert into car (make, model, price) values ('Ford', 'Bronco II', '64195.79');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '15389.72');
insert into car (make, model, price) values ('Ford', 'E-Series', '48925.69');
insert into car (make, model, price) values ('Ford', 'Freestar', '37428.10');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '65969.29');
insert into car (make, model, price) values ('Acura', 'CL', '75210.89');
insert into car (make, model, price) values ('Ford', 'Focus', '46675.59');
insert into car (make, model, price) values ('Audi', 'A8', '26209.17');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '14273.42');
insert into car (make, model, price) values ('Ford', 'Fairlane', '41353.25');
insert into car (make, model, price) values ('Nissan', 'Sentra', '39276.17');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '31933.26');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '47885.30');
insert into car (make, model, price) values ('Toyota', 'Prius', '2962.02');
insert into car (make, model, price) values ('Ferrari', '612 Scaglietti', '30583.60');
insert into car (make, model, price) values ('GMC', 'Savana Cargo Van', '55627.40');
insert into car (make, model, price) values ('Audi', 'A6', '27637.23');
insert into car (make, model, price) values ('Toyota', 'Solara', '47259.90');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '35531.88');
insert into car (make, model, price) values ('Isuzu', 'VehiCROSS', '74963.36');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '38471.91');
insert into car (make, model, price) values ('Buick', 'Electra', '14857.40');
insert into car (make, model, price) values ('Maserati', 'Biturbo', '21398.71');
insert into car (make, model, price) values ('BMW', '3 Series', '34913.99');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '67880.74');
insert into car (make, model, price) values ('Audi', 'A8', '10684.83');
insert into car (make, model, price) values ('Toyota', 'Sienna', '9270.38');
insert into car (make, model, price) values ('Suzuki', 'SX4', '16849.10');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '34882.01');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '91233.30');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '61098.81');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '3684.10');
insert into car (make, model, price) values ('GMC', 'Sonoma', '9198.97');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '42318.27');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '16186.77');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '68332.88');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '33688.77');
insert into car (make, model, price) values ('Infiniti', 'Q', '87772.72');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500HD', '91518.80');
insert into car (make, model, price) values ('BMW', '7 Series', '47513.96');
insert into car (make, model, price) values ('Maybach', '62', '79445.61');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '86298.45');
insert into car (make, model, price) values ('Nissan', 'Datsun/Nissan Z-car', '87299.78');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '46843.74');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '78463.34');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '50956.08');
insert into car (make, model, price) values ('Toyota', 'Camry', '3640.01');
insert into car (make, model, price) values ('Ford', 'Ranger', '25761.62');
insert into car (make, model, price) values ('Toyota', 'Paseo', '82091.56');
insert into car (make, model, price) values ('Saturn', 'S-Series', '25737.11');
insert into car (make, model, price) values ('GMC', 'Savana', '12243.02');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '70935.42');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '93637.87');
insert into car (make, model, price) values ('Mercury', 'Tracer', '36658.87');
insert into car (make, model, price) values ('Hummer', 'H2', '71888.08');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '74704.43');
insert into car (make, model, price) values ('Maserati', 'Quattroporte', '1379.24');
insert into car (make, model, price) values ('Ford', 'E-Series', '37038.79');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '22612.39');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '23523.97');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '77872.04');
insert into car (make, model, price) values ('Scion', 'tC', '78334.59');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '30149.77');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '53315.89');
insert into car (make, model, price) values ('Ford', 'Escape', '17452.12');
insert into car (make, model, price) values ('GMC', 'Vandura 1500', '80586.69');
insert into car (make, model, price) values ('Infiniti', 'FX', '37120.62');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '82010.30');
insert into car (make, model, price) values ('Ford', 'Fusion', '31710.41');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '58931.57');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '20791.58');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '54817.74');
insert into car (make, model, price) values ('Ford', 'E-Series', '98702.78');
insert into car (make, model, price) values ('Hyundai', 'XG350', '90021.86');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '20071.44');
insert into car (make, model, price) values ('Volkswagen', 'Routan', '81805.48');
insert into car (make, model, price) values ('Audi', 'A6', '52604.80');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '4693.14');
insert into car (make, model, price) values ('Infiniti', 'G', '81999.17');
insert into car (make, model, price) values ('Audi', 'S4', '75263.17');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '48911.20');
insert into car (make, model, price) values ('Maybach', '62', '3060.27');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '23222.35');
insert into car (make, model, price) values ('Saab', '9000', '32683.12');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '58866.76');
insert into car (make, model, price) values ('Nissan', '350Z', '58769.12');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '11513.25');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '39216.69');
insert into car (make, model, price) values ('Infiniti', 'I', '39723.27');
insert into car (make, model, price) values ('BMW', '325', '75529.55');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '66677.15');
insert into car (make, model, price) values ('Infiniti', 'Q', '18934.01');
insert into car (make, model, price) values ('Ram', '1500', '73522.68');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '72028.85');
insert into car (make, model, price) values ('Chevrolet', 'Cobalt SS', '65034.53');
insert into car (make, model, price) values ('Audi', 'A6', '68157.83');
insert into car (make, model, price) values ('Pontiac', 'Daewoo Kalos', '64196.69');
insert into car (make, model, price) values ('GMC', '2500', '56053.06');
insert into car (make, model, price) values ('Toyota', 'FJ Cruiser', '29507.45');
insert into car (make, model, price) values ('GMC', 'Sonoma', '10972.52');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '41830.13');
insert into car (make, model, price) values ('Honda', 'Passport', '58748.32');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '26130.20');
insert into car (make, model, price) values ('Mazda', 'Tribute', '50630.97');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G10', '43570.05');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '17183.07');
insert into car (make, model, price) values ('Maybach', '62', '64554.98');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '7915.76');
insert into car (make, model, price) values ('Mazda', 'MX-5', '95094.30');
insert into car (make, model, price) values ('Dodge', 'Sprinter', '3411.72');
insert into car (make, model, price) values ('Jaguar', 'XK Series', '82323.12');
insert into car (make, model, price) values ('Maserati', 'Spyder', '54982.89');
insert into car (make, model, price) values ('Nissan', 'Xterra', '85415.35');
insert into car (make, model, price) values ('Lexus', 'ES', '32733.78');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', '91183.81');
insert into car (make, model, price) values ('Volkswagen', 'Tiguan', '78230.60');
insert into car (make, model, price) values ('BMW', '7 Series', '45280.99');
insert into car (make, model, price) values ('Peugeot', '207', '58692.76');
insert into car (make, model, price) values ('Saab', '9-5', '4703.50');
insert into car (make, model, price) values ('BMW', '8 Series', '84766.47');
insert into car (make, model, price) values ('Porsche', '911', '75136.47');
insert into car (make, model, price) values ('MINI', 'Cooper', '68216.76');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '90807.22');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '75338.23');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max', '44899.93');
insert into car (make, model, price) values ('Ford', 'Explorer', '9301.79');
insert into car (make, model, price) values ('Buick', 'Terraza', '94558.60');
insert into car (make, model, price) values ('Cadillac', 'Eldorado', '30077.24');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '43015.60');
insert into car (make, model, price) values ('Lexus', 'LS', '25783.32');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '8903.25');
insert into car (make, model, price) values ('Chevrolet', '1500', '64315.20');
insert into car (make, model, price) values ('Volvo', 'S80', '93581.11');
insert into car (make, model, price) values ('Chrysler', 'Fifth Ave', '21768.72');
insert into car (make, model, price) values ('Mitsubishi', 'Expo', '95434.15');
insert into car (make, model, price) values ('Ford', 'Mustang', '2205.84');
insert into car (make, model, price) values ('Ford', 'E250', '73504.21');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '62489.31');
insert into car (make, model, price) values ('Bentley', 'Continental GT', '64402.48');
insert into car (make, model, price) values ('Ford', 'Taurus', '81820.09');
insert into car (make, model, price) values ('Volkswagen', 'CC', '95737.78');
insert into car (make, model, price) values ('Audi', 'A6', '26831.64');
insert into car (make, model, price) values ('Mitsubishi', 'RVR', '58631.08');
insert into car (make, model, price) values ('Maybach', '57', '80546.95');
insert into car (make, model, price) values ('Ford', 'Escape', '92360.13');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '47900.58');
insert into car (make, model, price) values ('Subaru', 'Tribeca', '5025.39');
insert into car (make, model, price) values ('Ford', 'E350', '43439.10');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '16688.85');
insert into car (make, model, price) values ('Chrysler', 'Voyager', '31796.91');
insert into car (make, model, price) values ('Volkswagen', 'Rabbit', '53198.97');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '36412.39');
insert into car (make, model, price) values ('Volkswagen', 'Tiguan', '94553.47');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '21717.97');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '38602.73');
insert into car (make, model, price) values ('Ford', 'Focus', '64753.17');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '57560.42');
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', '94056.11');
insert into car (make, model, price) values ('Lincoln', 'MKZ', '47899.43');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '30634.08');
insert into car (make, model, price) values ('Lotus', 'Elise', '3435.64');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '67978.11');
insert into car (make, model, price) values ('Geo', 'Tracker', '97286.84');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '12342.46');
insert into car (make, model, price) values ('Nissan', 'Frontier', '5788.99');
insert into car (make, model, price) values ('GMC', '3500', '18670.09');
insert into car (make, model, price) values ('Volkswagen', 'riolet', '33291.12');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '59335.79');
insert into car (make, model, price) values ('Suzuki', 'Aerio', '37929.31');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '12993.08');
insert into car (make, model, price) values ('Volvo', 'S80', '37078.63');
insert into car (make, model, price) values ('Lotus', 'Esprit', '37589.94');
insert into car (make, model, price) values ('Buick', 'Regal', '84896.08');
insert into car (make, model, price) values ('Dodge', 'Caliber', '69118.83');
insert into car (make, model, price) values ('Toyota', 'Avalon', '88809.56');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '49367.62');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '68093.13');
insert into car (make, model, price) values ('Audi', 'A8', '86119.91');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '89181.77');
insert into car (make, model, price) values ('Jeep', 'Liberty', '52355.76');
insert into car (make, model, price) values ('Audi', '80', '67581.94');
insert into car (make, model, price) values ('Infiniti', 'JX', '66771.93');
insert into car (make, model, price) values ('Ford', 'Mustang', '71762.41');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '48466.54');
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', '29467.72');
insert into car (make, model, price) values ('Chrysler', '300M', '99460.45');
insert into car (make, model, price) values ('Dodge', 'Avenger', '11501.31');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '52047.98');
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', '19669.81');
insert into car (make, model, price) values ('Buick', 'LeSabre', '82174.03');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '28833.29');
insert into car (make, model, price) values ('Buick', 'Enclave', '48047.60');
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', '27362.96');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '94490.67');
insert into car (make, model, price) values ('Audi', 'RS 6', '54673.25');
insert into car (make, model, price) values ('Subaru', 'Alcyone SVX', '1850.05');
insert into car (make, model, price) values ('Bentley', 'Azure', '9189.29');
insert into car (make, model, price) values ('Lexus', 'GX', '19350.89');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '36507.98');
insert into car (make, model, price) values ('Ford', 'E-350 Super Duty Van', '6307.92');
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', '21178.65');
insert into car (make, model, price) values ('Nissan', 'Xterra', '94175.70');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '53946.46');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '90680.02');
insert into car (make, model, price) values ('Mitsubishi', 'Raider', '91423.89');
insert into car (make, model, price) values ('Honda', 'Accord', '83616.82');
insert into car (make, model, price) values ('Volvo', 'XC90', '93153.23');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '90606.65');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '98674.39');
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', '28131.04');
insert into car (make, model, price) values ('Dodge', 'Ram Van 2500', '23644.41');
insert into car (make, model, price) values ('Acura', 'RDX', '21616.32');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '76746.34');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '63334.05');
insert into car (make, model, price) values ('Rolls-Royce', 'Ghost', '57223.65');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '28499.88');
insert into car (make, model, price) values ('Audi', 'A3', '88614.04');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '86399.19');
insert into car (make, model, price) values ('Nissan', 'Quest', '31357.91');
insert into car (make, model, price) values ('Cadillac', 'XLR-V', '66135.93');
insert into car (make, model, price) values ('Chevrolet', 'Sonic', '6845.57');
insert into car (make, model, price) values ('Honda', 'Accord', '54472.54');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '71788.33');
insert into car (make, model, price) values ('Saab', '9-5', '78830.61');
insert into car (make, model, price) values ('Volvo', 'XC70', '17888.57');
insert into car (make, model, price) values ('Dodge', 'D350 Club', '3692.10');
insert into car (make, model, price) values ('Toyota', 'RAV4', '73744.79');
insert into car (make, model, price) values ('Mazda', 'MX-6', '4733.82');
insert into car (make, model, price) values ('Lincoln', 'Continental', '23708.01');
insert into car (make, model, price) values ('Cadillac', 'CTS', '49560.46');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '44268.09');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '32210.66');
insert into car (make, model, price) values ('Toyota', 'Camry', '43568.19');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', '57944.56');
insert into car (make, model, price) values ('Ford', 'F250', '34239.39');
insert into car (make, model, price) values ('Geo', 'Tracker', '80616.45');
insert into car (make, model, price) values ('Mazda', 'MX-5', '74926.99');
insert into car (make, model, price) values ('Buick', 'Electra', '27970.19');
insert into car (make, model, price) values ('Lexus', 'GS', '20053.93');
insert into car (make, model, price) values ('Suzuki', 'Swift', '95329.01');
insert into car (make, model, price) values ('Lexus', 'LS', '25158.49');
insert into car (make, model, price) values ('Mitsubishi', 'Tredia', '85490.01');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '93217.81');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '12237.11');
insert into car (make, model, price) values ('Chevrolet', 'S10', '17270.09');
insert into car (make, model, price) values ('Ford', 'Edge', '64124.67');
insert into car (make, model, price) values ('Isuzu', 'Hombre Space', '51159.06');
insert into car (make, model, price) values ('Land Rover', 'Sterling', '50979.64');
insert into car (make, model, price) values ('Saturn', 'S-Series', '23931.36');
insert into car (make, model, price) values ('Mercury', 'Sable', '55626.61');
insert into car (make, model, price) values ('Maybach', '62', '22819.45');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '17109.07');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '50888.22');
insert into car (make, model, price) values ('Ford', 'F-Series', '76934.87');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '65045.73');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '64827.37');
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', '79232.07');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '62791.30');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '16719.36');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '78942.03');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '15503.61');
insert into car (make, model, price) values ('Bentley', 'Continental GTC', '57101.90');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '40050.94');
insert into car (make, model, price) values ('Jaguar', 'XF', '70912.33');
insert into car (make, model, price) values ('Lexus', 'IS F', '31922.97');
insert into car (make, model, price) values ('Toyota', 'Xtra', '38879.45');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '83241.91');
insert into car (make, model, price) values ('Lincoln', 'MKT', '97772.75');
insert into car (make, model, price) values ('BMW', 'X3', '89675.32');
insert into car (make, model, price) values ('Jaguar', 'XK Series', '66362.20');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '28141.01');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '24923.62');
insert into car (make, model, price) values ('Subaru', 'Tribeca', '1946.65');
insert into car (make, model, price) values ('BMW', '6 Series', '74680.54');
insert into car (make, model, price) values ('Ford', 'LTD', '79609.14');
insert into car (make, model, price) values ('Honda', 'Civic', '51569.31');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '31160.92');
insert into car (make, model, price) values ('Acura', 'RSX', '58859.52');
insert into car (make, model, price) values ('Jaguar', 'XK', '85064.11');
insert into car (make, model, price) values ('Ford', 'Windstar', '87402.40');
insert into car (make, model, price) values ('Jaguar', 'XJ', '28429.67');
insert into car (make, model, price) values ('Mazda', 'B-Series', '80458.63');
insert into car (make, model, price) values ('Nissan', 'Murano', '93728.20');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '3028.42');
insert into car (make, model, price) values ('Volkswagen', 'Golf III', '18739.92');
insert into car (make, model, price) values ('Ford', 'Explorer', '77232.34');
insert into car (make, model, price) values ('Chrysler', 'Voyager', '34032.01');
insert into car (make, model, price) values ('Volkswagen', 'Tiguan', '95658.83');
insert into car (make, model, price) values ('Buick', 'Electra', '95593.03');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed 3', '90435.33');
insert into car (make, model, price) values ('Ford', 'F250', '26532.83');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '71419.62');
insert into car (make, model, price) values ('Saab', '9000', '45872.43');
insert into car (make, model, price) values ('Dodge', 'Ram 1500 Club', '22058.89');
insert into car (make, model, price) values ('Saturn', 'VUE', '59681.45');
insert into car (make, model, price) values ('Mazda', '929', '16190.48');
insert into car (make, model, price) values ('Infiniti', 'G', '19294.13');
insert into car (make, model, price) values ('Audi', 'A6', '37061.82');
insert into car (make, model, price) values ('Pontiac', 'Vibe', '78898.54');
insert into car (make, model, price) values ('Lexus', 'RX', '17922.14');
insert into car (make, model, price) values ('Toyota', 'Echo', '19210.35');
insert into car (make, model, price) values ('GMC', '2500', '88523.89');
insert into car (make, model, price) values ('Chevrolet', '2500', '57001.58');
insert into car (make, model, price) values ('Buick', 'Terraza', '90728.92');
insert into car (make, model, price) values ('Ford', 'Econoline E150', '80671.72');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '38922.50');
insert into car (make, model, price) values ('Fillmore', 'Fillmore', '21352.13');
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', '77594.39');
insert into car (make, model, price) values ('Buick', 'LeSabre', '80513.96');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '21218.35');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '24909.67');
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', '39656.21');
insert into car (make, model, price) values ('Pontiac', 'Torrent', '25077.39');
insert into car (make, model, price) values ('BMW', 'Z3', '85202.98');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '9926.63');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '38089.73');
insert into car (make, model, price) values ('Audi', 'TT', '15330.27');
insert into car (make, model, price) values ('Ford', 'Transit Connect', '95767.63');
insert into car (make, model, price) values ('Lincoln', 'MKZ', '82908.45');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '91666.24');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '50440.93');
insert into car (make, model, price) values ('Bentley', 'Continental GTC', '80009.57');
insert into car (make, model, price) values ('Ford', 'F250', '18808.92');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '32148.94');
insert into car (make, model, price) values ('Audi', 'S6', '69429.48');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '78434.69');
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', '6798.83');
insert into car (make, model, price) values ('Infiniti', 'G', '24100.93');
insert into car (make, model, price) values ('Suzuki', 'Vitara', '57278.58');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '4964.38');
insert into car (make, model, price) values ('Infiniti', 'Q', '87117.91');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '65198.55');
insert into car (make, model, price) values ('Lincoln', 'Blackwood', '55590.04');
insert into car (make, model, price) values ('Audi', 'Cabriolet', '38336.15');
insert into car (make, model, price) values ('Chevrolet', 'Suburban', '99004.19');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '72566.79');
insert into car (make, model, price) values ('Ford', 'Taurus', '28492.17');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '14615.19');
insert into car (make, model, price) values ('Nissan', 'Murano', '63268.74');
insert into car (make, model, price) values ('Lexus', 'SC', '68552.29');
insert into car (make, model, price) values ('Cadillac', 'SRX', '68789.63');
insert into car (make, model, price) values ('Chevrolet', 'Venture', '16918.19');
insert into car (make, model, price) values ('Mercedes-Benz', 'W126', '61018.41');
insert into car (make, model, price) values ('Mazda', '626', '5112.89');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '15483.12');
insert into car (make, model, price) values ('Toyota', 'Sienna', '63904.65');
insert into car (make, model, price) values ('Chrysler', 'Cirrus', '70418.77');
insert into car (make, model, price) values ('Pontiac', 'GTO', '86933.94');
insert into car (make, model, price) values ('Lexus', 'LX', '97812.46');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '77644.81');
insert into car (make, model, price) values ('Subaru', 'XT', '84798.35');
insert into car (make, model, price) values ('Plymouth', 'Laser', '21421.13');
insert into car (make, model, price) values ('Land Rover', 'Freelander', '88482.44');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '80786.50');
insert into car (make, model, price) values ('Land Rover', 'Defender 90', '65555.84');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '24743.91');
insert into car (make, model, price) values ('Mazda', 'MPV', '14716.95');
insert into car (make, model, price) values ('Alfa Romeo', '164', '2359.95');
insert into car (make, model, price) values ('Audi', 'A4', '82945.56');
insert into car (make, model, price) values ('BMW', 'Z4', '40748.81');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '16619.27');
insert into car (make, model, price) values ('Porsche', '928', '55091.50');
insert into car (make, model, price) values ('GMC', '2500', '41844.55');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '84303.81');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '46156.86');
insert into car (make, model, price) values ('Ford', 'F-Series', '1060.34');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '69880.28');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '6549.33');
insert into car (make, model, price) values ('Mazda', 'B-Series', '67019.17');
insert into car (make, model, price) values ('Saab', '9-5', '78291.51');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '97886.05');
insert into car (make, model, price) values ('Toyota', '4Runner', '11422.24');
insert into car (make, model, price) values ('Toyota', 'Camry', '68583.96');
insert into car (make, model, price) values ('Audi', '4000CS Quattro', '94572.26');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '35239.58');
insert into car (make, model, price) values ('Mazda', 'Navajo', '52461.35');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '34463.74');
insert into car (make, model, price) values ('Ford', 'Tempo', '41024.65');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '73989.78');
insert into car (make, model, price) values ('Lincoln', 'Continental', '57779.09');
insert into car (make, model, price) values ('BMW', 'Z4', '52863.10');
insert into car (make, model, price) values ('Volvo', 'S80', '48722.25');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '39666.39');
insert into car (make, model, price) values ('Land Rover', 'LR4', '99956.83');
insert into car (make, model, price) values ('Bentley', 'Continental', '85221.73');
insert into car (make, model, price) values ('Dodge', 'Caliber', '98357.48');
insert into car (make, model, price) values ('Pontiac', 'Vibe', '60749.88');
insert into car (make, model, price) values ('Mazda', 'MX-6', '13832.16');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '55973.98');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '80826.08');
insert into car (make, model, price) values ('Ford', 'F350', '62234.34');
insert into car (make, model, price) values ('Lexus', 'IS', '53066.86');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '21064.73');
insert into car (make, model, price) values ('Kia', 'Amanti', '65259.45');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '29201.66');
insert into car (make, model, price) values ('Lexus', 'IS', '10520.79');
insert into car (make, model, price) values ('GMC', 'Sonoma', '82685.76');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '37119.30');
insert into car (make, model, price) values ('Austin', 'Mini Cooper S', '41928.64');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '6585.99');
insert into car (make, model, price) values ('Infiniti', 'M', '58024.02');
insert into car (make, model, price) values ('Acura', 'RSX', '72925.66');
insert into car (make, model, price) values ('Dodge', 'Viper RT/10', '58571.75');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '33891.42');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '46120.64');
insert into car (make, model, price) values ('Buick', 'Regal', '83933.36');
insert into car (make, model, price) values ('Pontiac', 'G5', '17877.55');
insert into car (make, model, price) values ('Honda', 'Civic', '87024.47');
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', '14167.50');
insert into car (make, model, price) values ('Lexus', 'ES', '38788.34');
insert into car (make, model, price) values ('MINI', 'Cooper Clubman', '27443.61');
insert into car (make, model, price) values ('Ford', 'F150', '51424.26');
insert into car (make, model, price) values ('Ford', 'Mustang', '55151.15');
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', '24900.59');
insert into car (make, model, price) values ('Mazda', 'RX-8', '20230.95');
insert into car (make, model, price) values ('GMC', 'Yukon', '74797.46');
insert into car (make, model, price) values ('Audi', 'A4', '7127.89');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '96280.06');
insert into car (make, model, price) values ('Isuzu', 'Rodeo Sport', '35991.38');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '62093.42');
insert into car (make, model, price) values ('Oldsmobile', '98', '17972.50');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '36524.43');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '92247.17');
insert into car (make, model, price) values ('Volvo', 'S40', '78193.39');
insert into car (make, model, price) values ('Isuzu', 'Amigo', '48487.21');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '38603.14');
insert into car (make, model, price) values ('Mazda', 'Navajo', '28002.97');
insert into car (make, model, price) values ('Honda', 'Fit', '14939.64');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '28122.89');
insert into car (make, model, price) values ('Volvo', 'XC70', '98858.77');
insert into car (make, model, price) values ('Volvo', 'C30', '64705.44');
insert into car (make, model, price) values ('Chevrolet', '3500', '39761.66');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '43534.75');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '74455.59');
insert into car (make, model, price) values ('Mazda', 'MX-5', '20423.83');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '91385.58');
insert into car (make, model, price) values ('Ford', 'Windstar', '38461.06');
insert into car (make, model, price) values ('Mitsubishi', 'Tundra', '18679.29');
insert into car (make, model, price) values ('Isuzu', 'Oasis', '7856.32');
insert into car (make, model, price) values ('Ford', 'E250', '65854.79');
insert into car (make, model, price) values ('BMW', 'Z4 M', '79035.03');
insert into car (make, model, price) values ('Chevrolet', 'Caprice', '29113.20');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '73020.96');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '93669.67');
insert into car (make, model, price) values ('Lexus', 'SC', '39583.35');
insert into car (make, model, price) values ('Maserati', 'Quattroporte', '91826.99');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '56593.12');
insert into car (make, model, price) values ('Mazda', 'MX-6', '5735.59');
insert into car (make, model, price) values ('Cadillac', 'STS', '92204.93');
insert into car (make, model, price) values ('BMW', 'X5', '93941.52');
insert into car (make, model, price) values ('BMW', 'Z3', '53032.08');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '9432.38');
insert into car (make, model, price) values ('Maybach', '57', '32767.78');
insert into car (make, model, price) values ('Ford', 'E150', '15295.34');
insert into car (make, model, price) values ('Lexus', 'LX', '22302.92');
insert into car (make, model, price) values ('Ford', 'Bronco', '99850.30');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '92653.58');
insert into car (make, model, price) values ('Mercury', 'Sable', '38587.55');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '64203.18');
insert into car (make, model, price) values ('Lincoln', 'MKS', '16107.43');
insert into car (make, model, price) values ('Ford', 'E-Series', '85673.02');
insert into car (make, model, price) values ('Mazda', '626', '91209.22');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '4410.38');
insert into car (make, model, price) values ('BMW', '325', '36769.88');
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G20', '58824.48');
insert into car (make, model, price) values ('Lexus', 'IS-F', '5778.66');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '3213.70');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '35457.87');
insert into car (make, model, price) values ('Dodge', 'Ramcharger', '17161.16');
insert into car (make, model, price) values ('Ford', 'F150', '65731.02');
insert into car (make, model, price) values ('Maserati', 'Quattroporte', '93555.94');
insert into car (make, model, price) values ('Toyota', '4Runner', '53585.69');
insert into car (make, model, price) values ('Jaguar', 'XK', '19823.32');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '79773.91');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '40757.75');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '45327.78');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '81554.12');
insert into car (make, model, price) values ('Mercedes-Benz', 'GL-Class', '43166.21');
insert into car (make, model, price) values ('BMW', 'X5', '36026.90');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '55367.66');
insert into car (make, model, price) values ('Volvo', 'XC70', '78291.49');
insert into car (make, model, price) values ('Ford', 'Ranger', '46393.89');
insert into car (make, model, price) values ('Cadillac', 'Seville', '82195.97');
insert into car (make, model, price) values ('Ford', 'Mustang', '24333.15');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '80444.32');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '54962.87');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '25006.24');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '10955.38');
insert into car (make, model, price) values ('Hyundai', 'XG300', '34745.19');
insert into car (make, model, price) values ('Bentley', 'Continental', '54145.39');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '24247.86');
insert into car (make, model, price) values ('Buick', 'Century', '69948.57');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '77986.66');
insert into car (make, model, price) values ('Kia', 'Rio', '57851.53');
insert into car (make, model, price) values ('Ford', 'Ranger', '27268.33');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '95930.18');
insert into car (make, model, price) values ('Mercedes-Benz', '400E', '77655.20');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '33156.11');
insert into car (make, model, price) values ('Dodge', 'Neon', '90852.67');
insert into car (make, model, price) values ('Volvo', 'C70', '29840.91');
insert into car (make, model, price) values ('Mercedes-Benz', '500SEC', '57876.19');
insert into car (make, model, price) values ('Volvo', '240', '35475.21');
insert into car (make, model, price) values ('Volkswagen', 'Fox', '78810.39');
insert into car (make, model, price) values ('Lexus', 'LS', '57401.40');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '58556.68');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '86263.00');
insert into car (make, model, price) values ('Saturn', 'Sky', '10933.18');
insert into car (make, model, price) values ('Volkswagen', 'Eos', '84843.13');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '21664.99');
insert into car (make, model, price) values ('BMW', 'Z4', '85888.19');
insert into car (make, model, price) values ('Ford', 'F350', '65416.94');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '34483.69');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '41610.97');
insert into car (make, model, price) values ('Porsche', '911', '80936.59');
insert into car (make, model, price) values ('BMW', '7 Series', '32961.30');
insert into car (make, model, price) values ('Chevrolet', 'Suburban', '45645.08');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '50429.79');
insert into car (make, model, price) values ('Subaru', 'SVX', '12362.28');
insert into car (make, model, price) values ('Lexus', 'LS', '29997.75');
insert into car (make, model, price) values ('Porsche', 'Panamera', '18369.88');
insert into car (make, model, price) values ('Holden', 'VS Commodore', '49901.49');
insert into car (make, model, price) values ('Porsche', '928', '62879.28');
insert into car (make, model, price) values ('Maserati', 'GranSport', '19991.25');
insert into car (make, model, price) values ('Dodge', 'Ram', '49465.51');
insert into car (make, model, price) values ('Ford', 'Ranger', '44630.29');
insert into car (make, model, price) values ('Mazda', 'MX-5', '48604.94');
insert into car (make, model, price) values ('Ford', 'Explorer', '81507.56');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '75598.10');
insert into car (make, model, price) values ('Buick', 'LeSabre', '7778.58');
insert into car (make, model, price) values ('Toyota', 'RAV4', '47462.44');
insert into car (make, model, price) values ('Ford', 'Aerostar', '2983.54');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '67412.79');
insert into car (make, model, price) values ('Audi', 'Q7', '76677.64');
insert into car (make, model, price) values ('Plymouth', 'Acclaim', '95730.90');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '78383.22');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '2941.55');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '93410.01');
insert into car (make, model, price) values ('Kia', 'Sorento', '87235.13');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '34992.60');
insert into car (make, model, price) values ('Nissan', '300ZX', '66282.93');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '40413.78');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '59699.30');
insert into car (make, model, price) values ('Audi', 'A4', '97411.77');
insert into car (make, model, price) values ('Morgan', 'Aero 8', '28383.08');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '67978.21');
insert into car (make, model, price) values ('Nissan', 'Altima', '44403.05');
insert into car (make, model, price) values ('Nissan', 'Quest', '2187.61');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '90282.35');
insert into car (make, model, price) values ('Chevrolet', 'S10', '11601.67');
insert into car (make, model, price) values ('Subaru', 'Impreza', '81921.09');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '94257.55');
insert into car (make, model, price) values ('Subaru', 'Impreza', '15518.04');
insert into car (make, model, price) values ('Daewoo', 'Nubira', '21040.42');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max', '41648.26');
insert into car (make, model, price) values ('Audi', 'A8', '54980.08');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '90228.41');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '59947.22');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '43723.53');
insert into car (make, model, price) values ('Acura', 'TL', '84308.82');
insert into car (make, model, price) values ('Mercury', 'Villager', '76298.72');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '62829.32');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '77676.65');
insert into car (make, model, price) values ('Toyota', 'T100', '45729.84');
insert into car (make, model, price) values ('Audi', '200', '28929.48');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '15224.21');
insert into car (make, model, price) values ('Cadillac', 'Eldorado', '70935.30');
insert into car (make, model, price) values ('Volvo', 'XC70', '10761.26');
insert into car (make, model, price) values ('Honda', 'Prelude', '98577.41');
insert into car (make, model, price) values ('Toyota', 'RAV4', '14592.54');
insert into car (make, model, price) values ('Lexus', 'GX', '53753.02');
insert into car (make, model, price) values ('Ford', 'Taurus', '6364.04');
insert into car (make, model, price) values ('Jaguar', 'XK', '68327.83');
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', '15950.61');
insert into car (make, model, price) values ('GMC', 'Yukon', '55744.89');
insert into car (make, model, price) values ('Volvo', 'S80', '39273.11');
insert into car (make, model, price) values ('Acura', 'NSX', '48892.43');
insert into car (make, model, price) values ('Toyota', 'Corolla', '28465.85');
insert into car (make, model, price) values ('Dodge', 'Durango', '70320.36');
insert into car (make, model, price) values ('Ford', 'Explorer', '92923.12');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '96842.86');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '17796.43');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '49742.53');
insert into car (make, model, price) values ('Nissan', 'Frontier', '65312.20');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '81430.17');
insert into car (make, model, price) values ('Plymouth', 'Fury', '7108.93');
insert into car (make, model, price) values ('Ford', 'Escort', '36024.19');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '35101.31');
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', '22863.81');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '95802.06');
insert into car (make, model, price) values ('Suzuki', 'Vitara', '61934.08');
insert into car (make, model, price) values ('Ford', 'Windstar', '73406.70');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '9944.10');
insert into car (make, model, price) values ('Ford', 'Expedition', '9206.61');
insert into car (make, model, price) values ('Acura', 'CL', '16132.00');
insert into car (make, model, price) values ('Chevrolet', 'Corsica', '94114.97');
insert into car (make, model, price) values ('Mazda', 'MX-6', '99935.63');
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', '76106.47');
insert into car (make, model, price) values ('Volvo', 'S60', '37212.90');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '42920.93');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '89465.41');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '20491.73');
insert into car (make, model, price) values ('Mazda', 'MX-6', '27071.85');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '37808.46');
insert into car (make, model, price) values ('Mercedes-Benz', 'R-Class', '90026.16');
insert into car (make, model, price) values ('Hyundai', 'Scoupe', '67042.26');
insert into car (make, model, price) values ('Dodge', 'Viper', '69960.15');
insert into car (make, model, price) values ('GMC', 'Safari', '81322.47');
insert into car (make, model, price) values ('Mazda', '626', '11711.59');
insert into car (make, model, price) values ('Suzuki', 'Verona', '53247.54');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '90935.86');
insert into car (make, model, price) values ('Chrysler', 'Cirrus', '62223.60');
insert into car (make, model, price) values ('Isuzu', 'Amigo', '46252.30');
insert into car (make, model, price) values ('Dodge', 'Viper', '68144.51');
insert into car (make, model, price) values ('Ford', 'Expedition EL', '51567.62');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 1500', '90866.50');
insert into car (make, model, price) values ('Lexus', 'IS', '18703.37');
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', '70606.72');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '73173.37');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '35786.08');
insert into car (make, model, price) values ('Chevrolet', 'Beretta', '88729.13');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '81881.14');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '3687.98');
insert into car (make, model, price) values ('Jeep', 'Liberty', '11902.66');
insert into car (make, model, price) values ('BMW', 'Z4', '65032.88');
insert into car (make, model, price) values ('Chevrolet', 'Express', '28015.07');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '37139.08');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '78465.28');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '51625.92');
insert into car (make, model, price) values ('Infiniti', 'QX56', '95033.26');
insert into car (make, model, price) values ('Lotus', 'Elise', '51901.29');
insert into car (make, model, price) values ('Mercury', 'Cougar', '16638.02');
insert into car (make, model, price) values ('Audi', 'A6', '32612.29');
insert into car (make, model, price) values ('Mazda', 'Familia', '43636.20');
insert into car (make, model, price) values ('Porsche', 'Boxster', '75353.87');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '81176.30');
insert into car (make, model, price) values ('Lotus', 'Esprit', '65536.05');
insert into car (make, model, price) values ('Audi', 'Coupe Quattro', '17174.50');
insert into car (make, model, price) values ('Hummer', 'H2', '12597.39');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '52838.36');
insert into car (make, model, price) values ('Mazda', '626', '66686.46');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '99582.84');
insert into car (make, model, price) values ('Lexus', 'ES', '92009.88');
insert into car (make, model, price) values ('Dodge', 'Caliber', '15206.50');
insert into car (make, model, price) values ('Bentley', 'Azure T', '27591.72');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '31070.35');
insert into car (make, model, price) values ('Chrysler', '300', '99852.86');
insert into car (make, model, price) values ('Toyota', 'TundraMax', '18255.08');
insert into car (make, model, price) values ('Toyota', 'Celica', '73173.06');
insert into car (make, model, price) values ('Ford', 'Club Wagon', '99878.18');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '83634.35');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '49757.15');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '43868.68');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '22152.78');
insert into car (make, model, price) values ('Oldsmobile', 'Alero', '48266.32');
insert into car (make, model, price) values ('Nissan', 'Altima', '46064.16');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '73619.92');
insert into car (make, model, price) values ('Eagle', 'Summit', '15807.92');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '56915.99');
insert into car (make, model, price) values ('Saab', '9-3', '5878.23');
insert into car (make, model, price) values ('Audi', 'A8', '31838.74');
insert into car (make, model, price) values ('Lexus', 'RX', '4866.12');
insert into car (make, model, price) values ('Mazda', 'Millenia', '97612.38');
insert into car (make, model, price) values ('Morgan', 'Aero 8', '38320.28');
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', '40340.85');
insert into car (make, model, price) values ('Ford', 'Laser', '65179.00');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '35283.56');
insert into car (make, model, price) values ('Pontiac', 'Firebird Formula', '80160.12');
insert into car (make, model, price) values ('Toyota', 'Supra', '14775.70');
insert into car (make, model, price) values ('Buick', 'Lucerne', '41677.84');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '47419.22');
insert into car (make, model, price) values ('GMC', '3500', '19501.91');
insert into car (make, model, price) values ('Daewoo', 'Leganza', '69973.61');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '62246.95');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '65556.96');
insert into car (make, model, price) values ('Infiniti', 'IPL G', '84877.77');
insert into car (make, model, price) values ('Lexus', 'SC', '35745.78');
insert into car (make, model, price) values ('BMW', 'X6', '15974.93');
insert into car (make, model, price) values ('Hyundai', 'Accent', '23078.41');
insert into car (make, model, price) values ('Chevrolet', 'Tracker', '62929.47');
insert into car (make, model, price) values ('Infiniti', 'Q', '31793.61');
insert into car (make, model, price) values ('Nissan', 'NX', '99274.96');
insert into car (make, model, price) values ('Dodge', 'Caliber', '34979.40');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '11995.73');
insert into car (make, model, price) values ('Oldsmobile', '88', '26689.36');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '60199.70');
insert into car (make, model, price) values ('Audi', 'Quattro', '98257.59');
insert into car (make, model, price) values ('GMC', '1500', '83264.86');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '35682.40');
insert into car (make, model, price) values ('Infiniti', 'G', '83979.45');
insert into car (make, model, price) values ('Lexus', 'IS', '87632.51');
insert into car (make, model, price) values ('Ford', 'Expedition', '16701.85');
insert into car (make, model, price) values ('Audi', 'S8', '36390.96');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '10622.34');
insert into car (make, model, price) values ('Acura', 'MDX', '77357.49');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '71222.60');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '82114.59');
insert into car (make, model, price) values ('Pontiac', 'Safari', '40246.43');
insert into car (make, model, price) values ('Honda', 'del Sol', '85116.77');
insert into car (make, model, price) values ('Mercury', 'Cougar', '88811.60');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '47819.81');
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', '38361.04');
insert into car (make, model, price) values ('Mitsubishi', 'Tredia', '76290.41');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '1591.52');
insert into car (make, model, price) values ('Mercury', 'Tracer', '81958.74');
insert into car (make, model, price) values ('Acura', 'ZDX', '95068.94');
insert into car (make, model, price) values ('Ford', 'Expedition', '15356.93');
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', '69194.89');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', '37024.33');
insert into car (make, model, price) values ('Ford', 'Flex', '11784.25');
insert into car (make, model, price) values ('Mercury', 'Topaz', '20041.71');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '6388.51');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '74703.95');
insert into car (make, model, price) values ('Infiniti', 'EX', '31972.22');
insert into car (make, model, price) values ('Saturn', 'Outlook', '75362.36');
insert into car (make, model, price) values ('Suzuki', 'Swift', '94947.25');
insert into car (make, model, price) values ('Ford', 'Escort', '19874.28');
insert into car (make, model, price) values ('Toyota', 'Paseo', '18894.40');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '51325.62');
insert into car (make, model, price) values ('Audi', 'TT', '64891.62');
insert into car (make, model, price) values ('GMC', '3500', '75160.17');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '58948.24');
insert into car (make, model, price) values ('Infiniti', 'JX', '13503.94');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '57903.63');
insert into car (make, model, price) values ('Nissan', '370Z', '89652.09');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '69882.01');
insert into car (make, model, price) values ('Dodge', 'Ram', '15785.37');
insert into car (make, model, price) values ('Isuzu', 'Amigo', '61996.11');
insert into car (make, model, price) values ('Subaru', 'Tribeca', '44699.11');
insert into car (make, model, price) values ('Maserati', 'GranSport', '76779.78');
insert into car (make, model, price) values ('Lexus', 'GS', '74756.54');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '99985.25');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '41405.68');
insert into car (make, model, price) values ('Nissan', 'Versa', '11213.75');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '70011.85');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '29515.72');
